Controllers/AssignmentController.cs
using QuanLyDuAn.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyDuAn.Controllers
{
	public class AssignmentController : Controller
	{
		// GET: Assignment
		public ActionResult Index()
		{
			AssignmentViewModel assignment = new AssignmentViewModel();
			return View(assignment);
		}

		[HttpGet]
		public ActionResult Add()
		{
			AssignmentViewModel assignment = new AssignmentViewModel();
			return View(assignment);
		}

		[HttpPost]
		public ActionResult Add(FormCollection form)
		{
			try
			{
				using (DBContext dbContext = new DBContext())
				{
					var task = form["task_id"];
					var user = form["user_id"];
					var item = new assignment();
					item.task_id = int.Parse(task.ToString());
					item.user_id = int.Parse(user.ToString());
					dbContext.assignment.Add(item);
					dbContext.SaveChanges();
				}
				ViewBag.message = "success";
			}
			catch (Exception)
			{
				ViewBag.message = "error";
			}
			return View("Add", new AssignmentViewModel());

		}

		[HttpGet]
		public ActionResult Edit(int id)
		{
			try
			{
				AssignmentViewModel assignment = new AssignmentViewModel();
				using (DBContext dbContext = new DBContext())
				{
					var assign = dbContext.assignment.Find(id);
					assignment.assign = assign;
				}
				return View(assignment);
			}
			catch (Exception)
			{

				return RedirectToAction("Index");
			}

		}

		[HttpPost]
		public ActionResult Edit(FormCollection form)
		{
			try
			{
				using (DBContext dbContext = new DBContext())
				{
					var id = form["id"];
					var task_id = form["task_id"];
					var user_id = form["user_id"];
					if (id != null)
					{
						var item = dbContext.assignment.Find(id);
						item.task_id = int.Parse(task_id.ToString());
						item.user_id = int.Parse(user_id.ToString());
						dbContext.SaveChanges();
					}
				}
				return RedirectToAction("Index");
			}
			catch (Exception)
			{
				ViewBag.message = "error";
				return View("Edit", new AssignmentViewModel());
			}
		}


		[HttpPost]
		public ActionResult Delete(int id)
		{
			using (DBContext context = new DBContext())
			{
				var item = context.assignment.FirstOrDefault(m => m.assignment_id == id);
				if (item != null)
				{
					context.assignment.Remove(item);
					context.SaveChanges();
				}
			}
			return RedirectToAction("Index");
		}
	}
}

Controllers/ProjectController.cs
using QuanLyDuAn.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyDuAn.Controllers
{
	public class ProjectController : Controller
	{
		// GET: Project
		public ActionResult Index()
		{
			return View(new ProjectViewModel());

		}

		[HttpGet]
		public ActionResult AddProject()
		{
			using (DBContext db = new DBContext())
			{
				ProjectViewModel projectViewModel = new ProjectViewModel();
				return View(projectViewModel);

			}
		}

		[HttpPost]
		public ActionResult Add(ProjectViewModel projectViewModel, FormCollection form)
		{
			using (DBContext db = new DBContext())
			{
				if (ModelState.IsValid)
				{
					var id = form["project_manager_id"];
					if (id != null)
					{
						projectViewModel.project.project_manager_id = int.Parse(id.ToString());
					}
					db.project.Add(projectViewModel.project);
					db.SaveChanges();
					ViewBag.message = "success";
				}
				else
				{
					ViewBag.message = "error";
				}
			}
			return View("AddProject", new ProjectViewModel());
		}

		[HttpGet]
		public ActionResult Edit(int id)
		{
			using (DBContext db = new DBContext())
			{
				var projectViewModel = new ProjectViewModel();
				var project = db.project.FirstOrDefault(m => m.project_id == id);
				projectViewModel.project = project;
				return View(projectViewModel);
			}
		}

		[HttpPost]
		public ActionResult Edit(ProjectViewModel projectViewModel, FormCollection form)
		{
			//string tmp = "<script>alert('123: " + projectViewModel.project.project_name + "')</script>";
			//Response.Write(tmp);
			using (DBContext context = new DBContext())
			{
				if (ModelState.IsValid)
				{
					var item = context.project.FirstOrDefault(m => m.project_id == projectViewModel.project.project_id);
					var id = form["project_manager_id"];
					if (id != null && item != null)
					{
						item.project_name = projectViewModel.project.project_name;
						item.start_date = projectViewModel.project.start_date;
						item.end_date = projectViewModel.project.end_date;
						item.project_manager_id = int.Parse(id.ToString());
						context.SaveChanges();
					}
				}
			}
			return View("Index",new ProjectViewModel());
		}

		[HttpGet]
		public ActionResult Delete(int id)
		{
			using(DBContext context = new DBContext())
			{
				var item = context.project.FirstOrDefault(m => m.project_id == id);
				if (item != null)
				{
					context.project.Remove(item);
					context.SaveChanges();
				}
			}
			return RedirectToAction("Index");
		}
	}
}

Controllers/TaskController.cs
using QuanLyDuAn.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyDuAn.Controllers
{
	public class TaskController : Controller
	{
		// GET: Task
		public ActionResult Index()
		{
			TaskViewModel t = new TaskViewModel();
			return View(t);
		}


		public ActionResult Add()
		{
			TaskViewModel t = new TaskViewModel();
			return View(t);
		}

		[HttpPost]
		public ActionResult Add(TaskViewModel t, FormCollection form)
		{
			using (DBContext db = new DBContext())
			{
				if (ModelState.IsValid)
				{
					var id = form["project_id"];
					if (id != null)
					{
						t.task.project_id = int.Parse(id.ToString());
					}
					db.task.Add(t.task);
					db.SaveChanges();
					ViewBag.message = "success";
				}
				else
				{
					ViewBag.message = "error";
				}
			}
			return View("Add", new TaskViewModel());
		}

		[HttpGet]
		public ActionResult Edit(int id)
		{
			using (DBContext db = new DBContext())
			{
				var taskViewModel = new TaskViewModel();
				var task = db.task.FirstOrDefault(m => m.task_id == id);
				taskViewModel.task = task;
				return View(taskViewModel);
			}
		}

		[HttpPost]
		public ActionResult Edit(TaskViewModel t, FormCollection form)
		{
			//string tmp = "<script>alert('123: " + t.task.task_id + "')</script>";
			//Response.Write(tmp);
			using (DBContext context = new DBContext())
			{
				if (ModelState.IsValid)
				{
					var item = context.task.FirstOrDefault(m => m.task_id == t.task.task_id);
					var id = form["project_id"];
					if (id != null && item != null)
					{
						item.task_name = t.task.task_name;
						item.start_date = t.task.start_date;
						item.end_date = t.task.end_date;
						item.status = t.task.status;
						item.project_id = int.Parse(id.ToString());
						context.SaveChanges();
					}
				}
			}
			return View("Index", new TaskViewModel());
		}


		[HttpGet]
		public ActionResult Delete(int id)
		{
			using (DBContext context = new DBContext())
			{
				var item = context.task.FirstOrDefault(m => m.task_id == id);
				if (item != null)
				{
					context.task.Remove(item);
					context.SaveChanges();
				}
			}
			return RedirectToAction("Index");
		}
	}
}

Controllers/UserController.cs
using QuanLyDuAn.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyDuAn.Controllers
{
	public class UserController : Controller
	{
		// GET: User
		public ActionResult Index()
		{
			using (DBContext db = new DBContext())
			{
				return View(db.users.ToList());
			}
		}

		[HttpGet]
		public ActionResult Add()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Add(users u)
		{
			using (DBContext dbContext = new DBContext())
			{
				if (ModelState.IsValid)
				{
					var item = dbContext.users.FirstOrDefault(m => m.user_name.Equals(u.user_name));
					if (item != null)
					{
						ViewBag.message = "error";
					}
					else
					{
						dbContext.users.Add(u);
						dbContext.SaveChanges();
						ViewBag.message = "success";
					}
				}
			}
			return View("Add");
		}

		[HttpGet]
		public ActionResult Edit(int id)
		{
			using (DBContext db = new DBContext())
			{
				var item = db.users.FirstOrDefault(m => m.user_id.Equals(id));
				return View(item);
			}
		}

		[HttpPost]
		public ActionResult Edit(users u)
		{
			using (DBContext db = new DBContext())
			{
				if (ModelState.IsValid)
				{
					var item = db.users.FirstOrDefault(m => m.user_id == u.user_id);
					if (item != null)
					{
						item.email = u.email;
						item.password = u.password;
						db.SaveChanges();
						return RedirectToAction("Index");
					}
				}
			}
			return View("Edit", new { u.user_id });
		}

		[HttpGet]
		public ActionResult Delete(int id)
		{
			using (DBContext db = new DBContext())
			{
				try
				{
					var item = db.users.FirstOrDefault(u => u.user_id == id);
					if (item != null)
					{
						db.users.Remove(item);
						db.SaveChanges();
					}
					return RedirectToAction("Index");
				}
				catch (Exception)
				{
					Response.Write("<script>alert('Người dùng này đang trong dự án khác.')</script>");
					return View("Index", db.users.ToList());
				}
			}
			
		}
	}
}

Views/Shared/_Layout.cshtml
@{
    var isLogin = Session["user"];
    QuanLyDuAn.Models.users user;
    if (isLogin != null)
    {
        user = isLogin as QuanLyDuAn.Models.users;
    }
    else
    {
        user = new QuanLyDuAn.Models.users();
    }
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>ADMIN - ABC GROUP</title>
    <link href="~/Content/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js"
            crossorigin="anonymous"></script>
    <link rel="icon"
          type="image/x-icon"
          href="https://upload.wikimedia.org/wikipedia/commons/1/19/Logo-ute_%282%29.png" />
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css"
          rel="stylesheet" />
    @RenderSection("css", required: false)
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
</head>

<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="/">ABC GROUP</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0"
                id="sidebarToggle"
                href="#!">
            <i class="fas fa-bars"></i>
        </button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0"></form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-auto float-right me-lg-4">
            <li class="nav-item dropdown" style="display: flex">
                @if (isLogin != null)
                {
                    <p class="nav-link">@user.user_name</p>
                }

                <a class="nav-link dropdown-toggle"
                   id="navbarDropdown"
                   href="#"
                   role="button"
                   data-bs-toggle="dropdown"
                   aria-expanded="false">
                    <i class="fas fa-user fa-fw"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-end"
                    aria-labelledby="navbarDropdown">
                    @if (isLogin != null)
                    {
                        <li>
                            @Html.ActionLink("Logout", "Index", "Logout", null, new { @class = "dropdown-item" })
                        </li>
                    }
                    else
                    {
                        <li>
                            @Html.ActionLink("Login", "Index", "Login", null, new { @class = "dropdown-item" })
                        </li>
                    }

                </ul>
            </li>
        </ul>
    </nav>
    @if (isLogin != null)
    {
        <div id="layoutSidenav">

            @if (isLogin != null)
            {
                <div id="layoutSidenav_nav">
                    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                        <div class="sb-sidenav-menu">
                            <div class="nav">
                                <div class="sb-sidenav-menu-heading">core</div>
                                <a class="nav-link" href="@Url.Action("Index","Home")">
                                    <div class="sb-nav-link-icon">
                                        <i class="fas fa-tachometer-alt"></i>
                                    </div>
                                    Dashboard
                                </a>
                                <a class="nav-link" href="@Url.Action("Index","Project")">
                                    <div class="sb-nav-link-icon">
                                        <i class="fas fa-sharp fa-solid fa-table-list"></i>
                                    </div>
                                    Projects
                                </a>
                                <a class="nav-link" href="@Url.Action("Index","User")">
                                    <div class="sb-nav-link-icon">
                                        <i class="fas fa-sharp fa-solid fa-user"></i>
                                    </div>
                                    Users
                                </a>
                                <a class="nav-link" href="@Url.Action("Index","Task")">
                                    <div class="sb-nav-link-icon">
                                        <i class="fa fa-sharp fa-solid fa-bars"></i>
                                    </div>
                                    Tasks
                                </a>
                                <a class="nav-link" href="@Url.Action("Index","Assignment")">
                                    <div class="sb-nav-link-icon">
                                        <i class="fa fa-sharp fa-solid fa-chart-simple"></i>
                                    </div>
                                    Assignments
                                </a>
                                <a class="nav-link" href="@Url.Action("Index","ProjectManager")">
                                    <div class="sb-nav-link-icon">
                                        <i class="fa fa-sharp fa-solid fa-chart-column"></i>
                                    </div>
                                    Project Manager
                                </a>

                            </div>
                        </div>
                        <div class="sb-sidenav-footer">
                            <div class="small">Logged in as:</div>
                            ABC GROUP
                        </div>
                    </nav>
                </div>



                <div id="layoutSidenav_content">
                    <main>
                        @RenderBody()
                    </main>
                    <footer class="py-4 mt-auto" style="background-color: #808080;">
                        <div class="container-fluid px-4">
                            <div class="text-center">
                                Copyright &copy; ABC GROUP
                            </div>
                        </div>
                    </footer>
                </div>
            }
            else
            {

            }


        </div>
    }
    else
    {
        <main id="layout_nologin">
            @RenderBody()
        </main>
        <footer class="py-4 mt-auto" style="background-color: #808080;">
            <div class="container-fluid px-4">
                <div class="text-center">
                    Copyright &copy; ABC GROUP
                </div>
            </div>
        </footer>
    }

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            crossorigin="anonymous"></script>
    <script src="~/Scripts/main.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest"
            crossorigin="anonymous"></script>
</body>
</html>