Models/project_manager.cs
namespace QuanLyDuAn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class project_manager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project_manager()
        {
            project = new HashSet<project>();
        }

        [Key]

        public int manager_id { get; set; }

        [StringLength(255)]
        public string manager_name { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> project { get; set; }
    }
}

Controllers/ProjectManagerController.cs
using QuanLyDuAn.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyDuAn.Controllers
{
	public class ProjectManagerController : Controller
	{
		// GET: ProjectManager
		public ActionResult Index()
		{
			using (DBContext db = new DBContext())
			{
				return View(db.project_manager.ToList());

			}
		}


		[HttpGet]
		public ActionResult AddProjectManager()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Add(project_manager _Manager)
		{
			if (ModelState.IsValid)
			{
				using (DBContext dbContext = new DBContext())
				{
					var item = new project_manager();
					item.manager_name = _Manager.manager_name;
					dbContext.project_manager.Add(item);
					dbContext.SaveChanges();
					ViewBag.message = "success";
				}
			}
			else
			{
				ViewBag.message = "error";
			}
			return RedirectToAction("Index");
		}
		[HttpGet]
		public ActionResult Edit(int id)
		{
			using (DBContext dB = new DBContext())
			{
				var item = dB.project_manager.FirstOrDefault(m => m.manager_id == id);
				return View(item);
			}
		}

		[HttpPost]
		public ActionResult Edit(project_manager manager)
		{
			using (DBContext dbContext = new DBContext())
			{
				var item = dbContext.project_manager.FirstOrDefault(m => m.manager_id == manager.manager_id);
				if (item != null)
				{
					item.manager_name = manager.manager_name;
					dbContext.SaveChanges();
					return RedirectToAction("Index");
				}
			}
			return View("Edit", new { manager.manager_id });
		}

		[HttpGet]
		public ActionResult delete(int id)
		{
			using(DBContext dB = new DBContext())
			{
				var item = dB.project_manager.FirstOrDefault(m=>m.manager_id==id);
				if(item != null)
				{
					dB.project_manager.Remove(item);
					dB.SaveChanges();
				}
			}
			return RedirectToAction("Index");

		}
	}
}

Views/ProjectManager/AddProjectManager.cshtml
@model QuanLyDuAn.Models.project_manager
@{
    ViewBag.Title = "AddProjectManager";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section css{
    <link rel="stylesheet" href="~/Content/add.css">
}
<section id="content" class="container">
    <div id="message">
        @if (ViewBag.Message == "success")
        {
            <p class='success'>Thêm mới thành công manager..</p>
        }
        else if (ViewBag.Message == "error")
        {
            <p class='error'>Lỗi thêm mới manager...</p>
        }
    </div>
    @using (Html.BeginForm("Add", "ProjectManager", FormMethod.Post))
    {
        <h1>Bảng nhập thông tin cho Project Manager</h1>
        <p>Vui lòng nhập đầy đủ thông tin để thêm mới Project Manager.</p>
        @Html.ValidationSummary(true);
        <label for="name"><b>Manager name</b></label>
        @Html.TextBoxFor(m => m.manager_name, new { placeholder = "Type your project manager name", required = "required", autofocus = "autofocus" })

        <div class="clearfix">
            <input type="submit" name="add" value="Add" class="btnAdd">
        </div>
    }
</section>

Views/ProjectManager/Edit.cshtml
@model QuanLyDuAn.Models.project_manager
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section css{
    <link rel="stylesheet" href="~/Content/add.css">
}
<section id="content" class="container">
    <div id="message">
        @if (ViewBag.Message == "success")
        {
            <p class='success'>Sửa thành công manager..</p>
        }
        else if (ViewBag.Message == "error")
        {
            <p class='error'>Lỗi sửa thông tin manager...</p>
        }
    </div>
    @using (Html.BeginForm("Edit", "ProjectManager", new { manager_id = Model.manager_id},FormMethod.Post,null))
    {
        <h1>Bảng nhập thông tin cho Project Manager</h1>
        <p>Vui lòng nhập đầy đủ thông tin để chỉnh sửa Project Manager.</p>
        @Html.ValidationSummary(true);
        <label for="name"><b>Manager name</b></label>
        @Html.TextBoxFor(m => m.manager_name, new { value = Model.manager_name, required = "required", autofocus = "autofocus" })

        <div class="clearfix">
            <input type="submit" name="edit" value="Edit" class="btnAdd">
        </div>
    }
</section>

Views/ProjectManager/Index.cshtml
@model List<QuanLyDuAn.Models.project_manager>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section css{
    <link rel="stylesheet" href="~/Content/list.index.css" type="text/css">
}

<div class="container-fluid px-4">
    <h1 class="mt-4">Dashboard</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">Dashboard</li>
        <li class="breadcrumb-item active">Project Manager</li>
    </ol>
    <hr />
    <div class="d-flex">
        @Html.ActionLink("Add", "AddProjectManager", "ProjectManager", null, new { @class = "btnAdd" })
    </div>
    <table border="1">
        <tr>
            <th>Manager ID</th>
            <th>Manager name</th>
            <th>Action</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.manager_id</td>
                <td>@item.manager_name</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "ProjectManager", new { id = item.manager_id }, null) |
                    @Html.ActionLink("Delete", "Delete", "ProjectManager",new {id=item.manager_id} , new { @onclick = "return confirm('Are you sure you want to delete this manager?');" })
                </td>
            </tr>
        }
    </table>
</div>